name: Gerar_APK_Final
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Este comando FABRICA o gradlew que está te dando erro de permissão
      - name: Criar Motor Gradle
        run: gradle wrapper

      - name: Compilar
        run: ./gradlew assembleDebug

      - name: Download
        uses: actions/upload-artifact@v4
        with:
          name: AppInstalador
          path: app/build/outputs/apk/debug/*.apk
